/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.autocompletor.test;

import java.awt.Color;
import org.autocompletor.free.AutoCompleter;
import org.autocompletor.free.AutoCompleterExtra;
import org.autocompletor.free.AutoCompleterInterface;
import org.autocompletor.free.Theme;

/**
 *
 * @author @mudassir
 * @modified @djasc1993 www.excellentsoft.net (2020)
 * @version 2.0.0
 * License:
 * This project has been cloned from https://github.com/mudassirbit/AutoCompleter, 
    * without forgetting to value @mudassir's effort, I have required to apply changes 
    * for the integration of my projects and since there has been no movement for 4 years With @mudassir,
    * I have uploaded a new repository
    * 
    * Note: Class names have been changes, just for simplicity of calling.
 */
public class TestFrame extends javax.swing.JFrame {
    
    private AutoCompleter autoComplete;
    /**
     * Creates new form TestFrame
     */
    public TestFrame() {
        initComponents();
        setLocationRelativeTo(null);  
        AutoCompleterExtra.DEBUG = true;
        autoComplete = new AutoCompleter(jTextField1,new Theme(Color.LIGHT_GRAY, Color.DARK_GRAY),(Object object_select) -> {
                ((ObjectCustom)  object_select).executeAction();
            //jTextField1.setText("");
            txtAction.setText("Action Select: "+object_select.toString());
            
        });
        
        autoComplete.setMethodSearch(AutoCompleterInterface.MODE_SEARCH_CHAR_CONTAINS); // default MODE_SEARCH_CHAR_CONTAINS
        autoComplete.setConcatSearch(false); // default false
        //autoComplete.setCharSeparate(", "); // default ""
        /*List<Object> items = new ArrayList<>();
        items.add("Apple");
        items.add("Orange");
        items.add("Mango");
        items.add("Grapes");
        items.add("Banana");
        items.add("Guava");
        autoComplete.addItems(items);
        */
        
        autoComplete.addItem(new ObjectCustom("APPLE UNO","ejecuta APPLE"));
        autoComplete.addItem(new ObjectCustom("HOME DOS","ejecuta HOME"));
        autoComplete.addItem(new ObjectCustom("HOME UNO","ejecuta HOME"));
        autoComplete.addItem(new ObjectCustom("TOMATO","ejecuta TOMATO"));
        autoComplete.addItem(new ObjectCustom("APPLE UNO","ejecuta APPLE"));
        autoComplete.addItem(new ObjectCustom("HOME DOS","ejecuta HOME"));
        autoComplete.addItem(new ObjectCustom("HOME UNO","ejecuta HOME"));
        autoComplete.addItem(new ObjectCustom("TOMATO","ejecuta TOMATO"));
        autoComplete.addItem(new ObjectCustom("APPLE UNO","ejecuta APPLE"));
        autoComplete.addItem(new ObjectCustom("HOME DOS","ejecuta HOME"));
        autoComplete.addItem(new ObjectCustom("HOME UNO","ejecuta HOME"));
        autoComplete.addItem(new ObjectCustom("TOMATO","ejecuta TOMATO"));
        autoComplete.addItem(new ObjectCustom("APPLE UNO","ejecuta APPLE"));
        autoComplete.addItem(new ObjectCustom("HOME DOS","ejecuta HOME"));
        autoComplete.addItem(new ObjectCustom("HOME UNO","ejecuta HOME"));
        autoComplete.addItem(new ObjectCustom("TOMATO","ejecuta TOMATO"));
        autoComplete.addItem(new ObjectCustom("APPLE UNO","ejecuta APPLE"));
        autoComplete.addItem(new ObjectCustom("HOME DOS","ejecuta HOME"));
        autoComplete.addItem(new ObjectCustom("HOME UNO","ejecuta HOME"));
        autoComplete.addItem(new ObjectCustom("TOMATO","ejecuta TOMATO"));
        autoComplete.addItem(new ObjectCustom("APPLE UNO","ejecuta APPLE"));
        autoComplete.addItem(new ObjectCustom("HOME DOS","ejecuta HOME"));
        autoComplete.addItem(new ObjectCustom("HOME UNO","ejecuta HOME"));
        autoComplete.addItem(new ObjectCustom("TOMATO","ejecuta TOMATO"));
        autoComplete.addItem(new ObjectCustom("APPLE UNO","ejecuta APPLE"));
        autoComplete.addItem(new ObjectCustom("HOME DOS","ejecuta HOME"));
        autoComplete.addItem(new ObjectCustom("HOME UNO","ejecuta HOME"));
        autoComplete.addItem(new ObjectCustom("TOMATO","ejecuta TOMATO"));
        
        //autoComplete.setNumberItems(15);//optional; we have default one
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        txtAction = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Autor:@mudassirbit | Modified: @djasc1993");

        jLabel2.setText("Write a word of the list:");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "APPLE UNO", "HOME DOS", "HOME UNO", "TOMATO", "APPLE UNO", "HOME DOS", "HOME UNO", "TOMATO", "APPLE UNO", "HOME DOS", "HOME UNO", "TOMATO", "APPLE UNO", "HOME DOS", "HOME UNO", "TOMATO", "APPLE UNO", "HOME DOS", "HOME UNO", "TOMATO", "APPLE UNO", "HOME DOS", "HOME UNO", "TOMATO", "APPLE UNO", "HOME DOS", "HOME UNO", "TOMATO" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setEnabled(false);
        jScrollPane1.setViewportView(jList1);

        txtAction.setEditable(false);
        txtAction.setText("Action Select:");

        jCheckBox1.setText("Concatened");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Search Start Letter", "Search Contain Letter", "Search End Letter" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtAction, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        autoComplete.setConcatSearch(jCheckBox1.isSelected());
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        autoComplete.setMethodSearch(jComboBox1.getSelectedIndex());
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TestFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtAction;
    // End of variables declaration//GEN-END:variables
}
